version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: movie-review-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - movie-review-network

  movies-review-server:
    build:
      context: ./movies
      dockerfile: Dockerfile
    image: movie-review-server:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/movie-api-db
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - movie-review-network

  movie-review-client:
    build:
      context: ./movies-client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8080/api/v1"
    image: movie-review-client:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - movies-review-server
    networks:
      - movie-review-network

networks:
  movie-review-network:
    driver: bridge

volumes:
  mongodb_data: